### ISSUE TITLE
Fix atomic density path if missing final `/`

### ISSUE THREAD

**Issue by danieleongari** [lsmo-epfl/aiida-ddec#16]
Chargemol has a nasty bug that make it crash if the path to the atomic densities does not ends with a `/`, for example:
```
    ddec_params = Dict(
        dict={
            'net charge': 0.0,
            'charge type': 'DDEC6',
            'periodicity along A, B, and C vectors': [True, True, True],
            'compute BOs': False,
            'atomic densities directory complete path': 'path/to/atomic_densities', #WILL FAIL! 
            'input filename': 'valence_density',
        })
```
Since this is a parameter that the user needs to provide every time, depending on the computer, make the plugin fix this problem by adding a `/` if missing.

**Comment by ltalirz** [comment]
Also ran into this again. It sucks.

@yakutovicha @danieleongari 
What if we create a little hack here:
 * We set an extra "ATOMIC_DENSITIES_DIRECTORY" on the code
 * We make  'atomic densities directory complete path' an optional key of the dict
 * If the dict key is not specified, it will search for the extra on the code. If the extra is not found it will raise an error.

It's not super-strictly following the guidelines, since you could lose provenance by deleting the extra again, but I think it's better than the status quo.

**Comment by ltalirz** [comment]
Could become even easier if those would be addressed
https://github.com/aiidateam/aiida-core/issues/420
https://github.com/aiidateam/aiida-core/issues/421
